### ISSUE TITLE
Change 'npm install crosis4furrets' to 'npm i crosis4furrets@0.0.1-beta.5' on the #README.md file

### ISSUE THREAD

**Issue by Hugoonreplit** [rayhanadev/crosis4furrets#2]
Hey @rayhanadev!

I've been checking crosis4furrets and it's so cool! I've been checking the #README.md file and the npm command to install crosis4furrest is `npm install crosis4furrets`. But on npm the command is ` npm i crosis4furrets@0.0.1-beta.5`. Should the README.md be changed for this one?

**Comment by rayhanadev** [comment]
Hi Hugo! Well the latest version of crosis4furrets that you _should_ be using is `crosis4furrets@1.2.2` not `crosis4furrets@0.0.1-beta.5`, the latter is before I took crosis4furrets public :).

By using `npm install crosis4furrets` you automatically get the latest version `1.2.2` and this package follows SemVer so the latest version will always have the highest number :).

I think you might've followed an old link, the link to the newest version of the package (and Usage which might help) is always [here](https://www.npmjs.com/package/crosis4furrets).

Hopefully that answers your question, best of luck! :)

**Comment by Hugoonreplit** [comment]
Thanks!
