### ISSUE TITLE
Invalid token on right sid

### ISSUE THREAD

**Issue by abdlmutii** [rayhanadev/crosis4furrets#7]
I got my replit sid, i pasted it to the token section. Didn't work, why?

**Comment by rayhanadev** [comment]
Did you URL decode your token? :) It has to be in `s:...` format :)

**Comment by abdlmutii** [comment]
> Did you URL decode your token? :) It has to be in `s:...` format :)

Yes i did url decode it. unfortunately didn't work

**Comment by abdlmutii** [comment]
Nvm it was my own problem lol
